name: Build Apps

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Crear .env
        shell: pwsh
        run: |
          "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" | Out-File -Encoding utf8 .env
          "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" | Out-File -Append -Encoding utf8 .env

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
          pip install PyQt6-WebEngine
          pip install spotipy
          pip install python-dotenv
          pip install supabase
          pip install requests

      - name: Build Windows
        run: |
          pyinstaller --windowed --noconfirm --clean --onedir --name SpotifyPlaylistPro --add-data ".env;." app.py

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: SpotifyPlaylistPro_Windows
          path: dist/SpotifyPlaylistPro

  build-macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Crear .env
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt6
          pip install PyQt6-WebEngine
          pip install spotipy
          pip install python-dotenv
          pip install supabase
          pip install requests

      - name: Build macOS
        run: |
          pyinstaller \
          --windowed \
          --noconfirm \
          --clean \
          --onedir \
          --name SpotifyPlaylistPro \
          --add-data ".env:." \
          app.py

      - name: Crear ZIP macOS
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent \
          SpotifyPlaylistPro.app \
          SpotifyPlaylistPro_macOS.zip

      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: SpotifyPlaylistPro_macOS
          path: dist/SpotifyPlaylistPro_macOS.zip
